apiVersion: apps/v1
kind: Deployment
metadata:
  name: watson-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  replicas: 2
  selector:
    matchLabels:
      app: api-watson
  template: 
    metadata:  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8082"              
      labels:
        app: api-watson
    spec:            
      containers:
      - name: api-watson        
        image: jeanlucafp/watsonapi:latest
        ports:
        - containerPort: 8082        
        env:
          - name: MONGODB_URI
            value: mongodb://mongodbuser:mongodbpwd@mongo-service:27017/admin
          - name: ASSISTANT_ID
            value: <ASSISTANT_ID>
          - name: ASSISTANT_IAM_APIKEY
            value: <ASSISTANT_IAM_APIKEY>